# Use a base Python image
FROM python:3.10-slim

# Install system dependencies
RUN echo "deb http://deb.debian.org/debian bookworm main contrib non-free" > /etc/apt/sources.list && \
    echo "deb http://deb.debian.org/debian-security bookworm-security main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb http://deb.debian.org/debian bookworm-updates main contrib non-free" >> /etc/apt/sources.list && \
    apt-get update && apt-get install -y \
    git \
    unrar \
    p7zip-full \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry
RUN pip install poetry

# Add Poetry to PATH
ENV PATH="/root/.local/bin:$PATH"

# Configure Poetry to create virtual environments in the project directory
RUN poetry config virtualenvs.in-project true

# Set up a working directory
WORKDIR /app

# Copy project files (if any)
COPY . /app/

# Install project dependencies using Poetry
RUN poetry install --no-root

# Set up METAFLOW
ENV METAFLOW_USER=metaflow_user

# Activate the virtual environment
RUN echo "source /app/.venv/bin/activate" >> ~/.bashrc

# Specify the default command to run when the container starts
CMD ["/bin/bash"]